#### 01- Loading Libraries

In [57]:
import numpy as np
import pandas as pd
from pysus.online_data.SIH import download
from ftplib import FTP

#### 02- Importing Data

In [69]:
vars = ['N_AIH', 'IDADE', 'SEXO', 'UF_ZI', 'NUM_FILHOS', 'INSTRU', 'MORTE', 'CID_MORTE', 'DIAS_PERM', 'DIAG_PRINC', 'DIAG_PRINC', 'DIAG_SECUN', 'DT_INTER', 'ANO_CMPT', 'MES_CMPT', 'MARCA_UTI', 'UTI_MES_TO', 'INFEHOSP']
ufs = ['ac', 'al', 'ap', 'am', 'ba', 'ce', 'df', 'es', 'go', 'ma', 'mt', 'ms', 'mg', 'pa', 'pb', 'pr', 'pe', 'pi', 'rj', 'rn', 'rs', 'ro', 'rr', 'sc', 'sp', 'se', 'to']
years = [2021]
months = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
cids = ['A90', 'A900']

In [70]:
for year in years:
    for month in months:
        for uf in ufs:   
            df = download(uf, year, month)
            df = df[['N_AIH', 'IDADE']]
#df = df.filter(vars)

In [60]:
df.head()

,N_AIH,IDADE,SEXO,UF_ZI,NUM_FILHOS,INSTRU,MORTE,CID_MORTE,DIAS_PERM,DIAG_PRINC,DIAG_PRINC,DIAG_SECUN,DT_INTER,ANO_CMPT,MES_CMPT,MARCA_UTI,UTI_MES_TO,INFEHOSP
0,1222100340571,35,1,120000,0,0,0,0000,1,M242,M242,0000,20220722,2022,09,00,0,
1,1222100290565,36,3,120000,0,0,0,0000,2,O800,O800,0000,20220709,2022,09,00,0,
2,1222100290972,15,3,120000,0,0,0,0000,1,O809,O809,0000,20220711,2022,09,00,0,
3,1222100227800,28,3,120000,0,0,0,0000,4,O200,O200,0000,20220530,2022,09,00,0,
4,1222100228240,40,3,120000,0,0,0,0000,3,O234,O234,0000,20220531,2022,09,00,0,